### ISSUE TITLE
I'm using unsigned char

### ISSUE THREAD

**Issue by SephVelut** [dpirch/libfvad#5]
My audio data is in the form of unsigned char* arrays.  fvad_process takes a signed short. Do I need to just convert from char to short? Will there be a loss of correctness as far as the vad is concerned?

**Comment by dpirch** [comment]
This depends on what format your audio data is in. The chars may not be individual samples, but bytes of audio data with larger samples, for example 16-bit samples where each sample takes up two bytes of the array.

If you know your array contains signed 16-bit samples with the correct endianness, then you can just cast the array to (int16_t*) and pass it to the library (in chunks with the required length, see comment in fvad.h). Otherwise you would have to calculate the individual sample values first.

To check if your data is signed 16-bit audio, you could write it to a file (with fwrite) and try playing it with ffplay (part of [FFmpeg](https://ffmpeg.org/)), for example
```
ffplay -f s16le -ar 8k -ac 1 yourfile.raw
```
(for 8kHz sample rate, and assuming your system is little-endian).

**Comment by SephVelut** [comment]
Thank you. I'll close this as its not an issue and may report back once I've got around to implementing the cast. Most likely I need shift the individual bytes to two bytes in a int16_t variable.
